export const LIST_ALL_UNIVERSITIES = "LIST_ALL_UNIVERSITIES";
export const LIST_ALL_LEADS = "LIST_ALL_LEADS";
export const LIST_ALL_APPLICATIONS = "LIST_ALL_APPLICATIONS";
export const LIST_PROGRAMMS = "LIST_PROGRAMMS";
export const LIST_ALL_CURRENCIES = "LIST_ALL_CURRENCIES";
export const LIST_ALL_BACKUPS = "LIST_ALL_BACKUPS";
export const LIST_ALL_BRANCHES = "LIST_ALL_BRANCHES";
export const LIST_ALL_USERS = "LIST_ALL_USERS";
export const LIST_CURRENT_USER = "LIST_CURRENT_USER";
export const LIST_ALL_ACTIVITIES = "LIST_ALL_ACTIVITIES";
export const LIST_ALL_PROERTIES = "LIST_ALL_PROERTIES";
export const LIST_ALL_List_LEADS = "LIST_ALL_List_LEADS";

//
export const VIEW_UNIVERSITY_DETAILS = "VIEW_UNIVERSITY_DETAILS";
export const VIEW_LEAD_DETAILS = "VIEW_LEAD_DETAILS";
export const APPLICATION_DETAILS = "APPLICATION_DETAILS";
export const VIEW_PROGRAMME_DETAILS = "VIEW_PROGRAMME_DETAILS";
export const VIEW_CURRENCY_DETAILS = "VIEW_CURRENCY_DETAILS";
export const VIEW_ALL_BRANCH = "VIEW_ALL_BRANCH";
export const VIEW_ALL_USERS = "VIEW_ALL_USERS";
export const DELETE_BACKUP_FILE = "DELETE_BACKUP_FILE";
export const DOWNLOAD_BACKUP_FILE = "DOWNLOAD_BACKUP_FILE";
export const RESTORE_BACKUP_FILE = "RESTORE_BACKUP_FILE";
export const VIEW_ALL_CURRECY = "VIEW_ALL_CURRECY";

// http://localhost:8080/v1/front/activities/list

// Anasite - Edits
export const VIEW_PROGRAM_LEVEL = "VIEW_PROGRAM_LEVEL";
export const LIST_ALL_PROGRAM_LEVELS = "LIST_ALL_PROGRAM_LEVELS";
//
export const VIEW_PROGRAM_CATEGORY = "VIEW_PROGRAM_CATEGORY";
export const LIST_ALL_PROGRAM_CATEGORYS = "LIST_ALL_PROGRAM_CATEGORYS";
//
export const VIEW_QUALIFICATION_TYPE = "VIEW_QUALIFICATION_TYPE";
export const LIST_ALL_QUALIFICATION_TYPES = "LIST_ALL_QUALIFICATION_TYPES";
//
export const VIEW_UNIVERSITY_TYPE = "VIEW_UNIVERSITY_TYPE";
//
export const LIST_ALL_UNIVERSITY_TYPES = "LIST_ALL_UNIVERSITY_TYPES";
export const VIEW_LEAD_GROUP = "VIEW_LEAD_GROUP";
export const LIST_ALL_LEAD_GROUPS = "LIST_ALL_LEAD_GROUPS";
//
export const VIEW_INTERESTED_PROGRAM = "VIEW_INTERESTED_PROGRAM";
export const LIST_ALL_INTERESTED_PROGRAMS = "LIST_ALL_INTERESTED_PROGRAMS";
//
export const VIEW_APPLICATION_MODULE_STATUS = "VIEW_APPLICATION_MODULE_STATUS";
export const LIST_ALL_APPLICATION_MODULE_STATUSS =
  "LIST_ALL_APPLICATION_MODULE_STATUSS";
//
export const VIEW_LEADS_MANAGMENT_MODULE_STATUS =
  "VIEW_LEADS_MANAGMENT_MODULE_STATU";
export const LIST_ALL_LEADS_MANAGMENT_MODULE_STATUS =
  "LIST_ALL_LEADS_MANAGMENT_MODULE_STATUS";
//
export const VIEW_INVOICE_MODULE_STATUS = "VIEW_INVOICE_MODULE_STATUS";
export const LIST_ALL_INVOICE_MODULE_STATUSS =
  "LIST_ALL_INVOICE_MODULE_STATUSS";
//
// Module: Invoice (1)
export const VIEW_COMMISSION_INVOICE = "VIEW_COMMISSION_INVOICE";
export const LIST_ALL_COMMISSION_INVOICES = "LIST_ALL_COMMISSION_INVOICES";
export const EDIT_COMMISSION_INVOICE = "EDIT_COMMISSION_INVOICE";
export const DELETE_COMMISSION_INVOICE = "DELETE_ALL_COMMISSION_INVOICES";
//
// Module: Invoice (2)
export const VIEW_GENERAL_INVOICE = "VIEW_GENERAL_INVOICE";
export const LIST_ALL_GENERAL_INVOICES = "LIST_ALL_GENERAL_INVOICES";
export const EDIT_GENERAL_INVOICE = "EDIT_GENERAL_INVOICE";
export const DELETE_GENERAL_INVOICE = "DELETE_ALL_GENERAL_INVOICES";
//
// Billing/Mailing
export const VIEW_BILLING_INFO = "VIEW_BILLING_INFO";
export const LIST_ALL_BILLING_INFOS = "LIST_ALL_BILLING_INFOS";
export const VIEW_MAILING_INFO = "VIEW_MAILING_INFO";
export const LIST_ALL_MAILING_INFOS = "LIST_ALL_MAILING_INFOS";

// Login type

export const SING_IN = "SING_IN";

// Module: Accounting (Sale)
export const VIEW_SALE = "VIEW_SALE";
export const LIST_ALL_SALES = "LIST_ALL_SALES";
//
// Module: Accounting (CostOfSale)
export const VIEW_COST_OF_SALE = "VIEW_COST_OF_SALE";
export const LIST_ALL_COST_OF_SALES = "LIST_ALL_COST_OF_SALES";
//
// Module: Accounting (Expenses)
export const VIEW_EXPENSE = "VIEW_EXPENSE";
export const LIST_ALL_EXPENSES = "LIST_ALL_EXPENSES";
//
// Module: Accounting (DepitAndCredit)
export const VIEW_DEPIT_AND_CREDIT = "VIEW_DEPIT_AND_CREDIT";
export const LIST_ALL_DEPIT_AND_CREDITS = "LIST_ALL_DEPIT_AND_CREDITS";
//
